name: Run Scraper Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # This cron expression runs the workflow every 5 minutes
  # You can also manually trigger it if needed (optional)
  workflow_dispatch:

jobs:
  scraper-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper script
        run: |
          python scraper.py
