name: Periodic Web Scraping

on:
  schedule:
    # This will run the action once every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows you to trigger the action manually

jobs:
  scrape-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium chromedriver_autoinstaller beautifulsoup4

    - name: Run scraping script
      run: python scrape.py
