name: Run Selenium Script

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run_selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install webdriver-manager
          sudo apt-get install -y chromium-browser

      - name: Run Selenium script
        run: |
          DISPLAY=:99.0 python gsearch.py
        env:
          DISPLAY: :99
          CHROME_BIN: /usr/bin/chromium-browser
          CHROME_DRIVER: /usr/lib/chromium-browser/chromedriver
